version: "2.0"
services:
  redis:
    image: redis
    command: >
      --requirepass 123456
  splash:
    image: scrapinghub/splash
  haipproxy:
    image: registry.cn-hangzhou.aliyuncs.com/weakiwi/haipproxy-alpine-image:stable
    command: sh run.sh
    volumes:
      - .:/haipproxy
    ports:
      - "3128"
    links:
      - redis
      - splash
